<?php

/**
 * @file
 * Contains hook for Ingredient Term module.
 */

declare(strict_types = 1);

use Drupal\node\NodeInterface;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_entity_type_presave().
 */
function ingredient_term_node_presave(NodeInterface $node): void {
  $material = $node->get('field_ingredients')->value;
  $lines = explode(PHP_EOL, (string) $material);
  foreach ($lines as $line) {
    $trimmed_line = trim($line);
    $ingredients = explode(' ', $trimmed_line);
    $element = end($ingredients);
    $terms = taxonomy_term_load_multiple_by_name($element, 'ingredients_vocab');
    if ($terms) {
      $term = reset($terms);
    }
    else {
      $term = Term::create([
        'name' => $element,
        'vid' => 'ingredients_vocab',
      ]);
      $term->save();
    }
    $recipe_term_id = $term->id();
    $node->field_ingredient_terms->set($recipe_term_id);
  }
}
