<?php

/**
 * @file
 * Contains hook for Ingredient Term module.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_entity_presave().
 */
function ingredient_term_entity_presave(EntityInterface $entity) {
	if ($entity->getEntityTypeId() == 'node' && $entity->getType() == 'article') {
    $material = $entity->get('field_ingredients')->value;  
    $ingredients = explode(' ', $material);
    foreach ($ingredients as $ingredient) {
      $term->create(array(
        'name' => $ingredient,
        'vid' => 'ingredient_vocab',
      ))->save();
    }
  }
}
